Gradle user guide
SpineEventEngine/SpineEventEngine.github.io pull request #370
Opened 2020-08-18 12:13 UTC by dmdashenkov

2020-08-25 12:58 UTC, dmdashenkov commented
@armiol, PTAL.

2020-08-25 13:37 UTC, armiol requested changes
@dmdashenkov please see my comments.

2020-08-25 13:37 UTC, armiol commented on docs/guides/gradle.md
> +The idea is to use Gradle subprojects for different parts of the system.
Let's connect this sentence to the previous one and the content which follows after. 

Something like this:

```
We recommend having separate Gradle subprojects for domain model definition, server 
implementation, and client code. Bootstrap is applied a bit differently in each
of these cases.
```

Also, the previous sentence says nothing about the model. Maybe we could rewrite it to give a more generic definition for the plugin per se:

```
Spine Bootstrap plugin (Bootstrap for short) serves to automate the configuration of the modules
in your Spine-based app.
```

2020-08-25 13:37 UTC, armiol commented on docs/guides/gradle.md
> +One subproject would contain Protobuf definitions for the domain model. This subproject is
I would say

`Let's assume one of the subprojects contains...`

2020-08-25 13:37 UTC, armiol commented on docs/guides/gradle.md
> +typically called `model`. If the system contains more than one Bounded Context, there could be
Let's first say how to do that for a single subproject, in detail.

Then, let's mention there may be several contexts. And how to wire them up etc.

2020-08-25 13:37 UTC, armiol commented on docs/guides/gradle.md
> +### Java implementation
`Java server implementation`?

2020-08-25 13:37 UTC, armiol commented on docs/guides/gradle.md
> +Each Bounded Context should have a separate Gradle subproject for implementing server-side
The idea of speaking of multiple contexts is that a reader obtains a more complex picture in her mind. And the problem here is that it's not likely what a first-learning reader starts from. I mean, even if they have multiple contexts, they are not going to deal with many of them right away knowing nothing of the Spine and the Gradle configuration.

When learning how to do things, it's always a good idea to show a simple and streamlined flow. And then have a more complex abstraction over it. Applying to this article, I would describe how things work for a single bounded context first. And then I would have a separate section (or maybe even another article), where the problem of inter-dependencies would be covered — as it ain't a simple thing at all, it's not just the dependency configuration.

2020-08-25 13:37 UTC, armiol commented on docs/guides/gradle.md
> +these modules, as long as those types are internal to the server and are not a part of
This is a tricky part. As a first-time reader, would you want to learn about the existence of "internal" Proto types from this article? I think, not.

2020-08-25 13:37 UTC, armiol commented on docs/guides/gradle.md
> +tasks The tasks are:
Judging on the "verbose" word, this section should speak of a fine-tuning for the model compiler. However, to me, it looks more like a quick reference.  As a reader, what I would want to do with this knowledge? Do I ever use these tasks, and if yes, then when and why?

We should either give some examples or just move this content to the `README.md` of the respective module and just provide readers with a link.

2020-08-25 13:37 UTC, armiol commented on docs/guides/gradle.md
> + - `mergeDescriptorSet` & `mergeTestDescriptorSet` — generate a merged Protobuf type descriptor set
If we speak "[task] deletes" in the `preClean` section, we should speak "generates" etc in the following sections as well.

2020-08-25 16:04 UTC, dmdashenkov commented
@armiol, PTAL again.

2020-08-25 20:05 UTC, armiol reviewed
@dmdashenkov this is much-much better than the last time. I'd like to discuss one thing (see my comment) with you though.

2020-08-25 20:05 UTC, armiol commented on docs/guides/gradle.md
> +generated from Protobuf.
Let's discuss the original idea of this section tomorrow in person. I don't fully understand what you mean here :(

2020-08-25 20:05 UTC, armiol commented on docs/guides/gradle.md
> +    implenemtation(project(':server'))
Please fix a typo.

Ideally, we would want to refer to some code in a real project instead. Not sure it exists now, but can we use `todo-list`?

2020-08-26 10:28 UTC, dmdashenkov commented
@armiol, PTAL again. If needed let's discuss if the provided explanations are detailed enough.

2020-08-26 13:58 UTC, armiol approved these changes

2020-08-26 13:58 UTC, armiol commented on docs/guides/gradle.md
> +which may provide the right API.
Maybe `the fine-grained API`?

2020-08-26 14:03 UTC, merged